// Data 114 Surat Al-Qur'an
// Format: { number, latin, arabic, verses, meaning }
const SURAHS = [
  { number: 1,   latin: "Al-Fatihah",     arabic: "الفاتحة",      verses: 7,   meaning: "Pembuka" },
  { number: 2,   latin: "Al-Baqarah",     arabic: "البقرة",       verses: 286, meaning: "Sapi Betina" },
  { number: 3,   latin: "Ali 'Imran",     arabic: "آل عمران",     verses: 200, meaning: "Keluarga Imran" },
  { number: 4,   latin: "An-Nisa'",       arabic: "النساء",       verses: 176, meaning: "Wanita" },
  { number: 5,   latin: "Al-Ma'idah",     arabic: "المائدة",      verses: 120, meaning: "Hidangan" },
  { number: 6,   latin: "Al-An'am",       arabic: "الأنعام",      verses: 165, meaning: "Binatang Ternak" },
  { number: 7,   latin: "Al-A'raf",       arabic: "الأعراف",      verses: 206, meaning: "Tempat Tertinggi" },
  { number: 8,   latin: "Al-Anfal",       arabic: "الأنفال",      verses: 75,  meaning: "Rampasan Perang" },
  { number: 9,   latin: "At-Taubah",      arabic: "التوبة",       verses: 129, meaning: "Pengampunan" },
  { number: 10,  latin: "Yunus",          arabic: "يونس",         verses: 109, meaning: "Nabi Yunus" },
  { number: 11,  latin: "Hud",            arabic: "هود",          verses: 123, meaning: "Nabi Hud" },
  { number: 12,  latin: "Yusuf",          arabic: "يوسف",         verses: 111, meaning: "Nabi Yusuf" },
  { number: 13,  latin: "Ar-Ra'd",        arabic: "الرعد",        verses: 43,  meaning: "Guruh" },
  { number: 14,  latin: "Ibrahim",        arabic: "إبراهيم",      verses: 52,  meaning: "Nabi Ibrahim" },
  { number: 15,  latin: "Al-Hijr",        arabic: "الحجر",        verses: 99,  meaning: "Gunung Al-Hijr" },
  { number: 16,  latin: "An-Nahl",        arabic: "النحل",        verses: 128, meaning: "Lebah" },
  { number: 17,  latin: "Al-Isra'",       arabic: "الإسراء",      verses: 111, meaning: "Perjalanan Malam" },
  { number: 18,  latin: "Al-Kahf",        arabic: "الكهف",        verses: 110, meaning: "Gua" },
  { number: 19,  latin: "Maryam",         arabic: "مريم",         verses: 98,  meaning: "Maryam" },
  { number: 20,  latin: "Taha",           arabic: "طه",           verses: 135, meaning: "Ta Ha" },
  { number: 21,  latin: "Al-Anbiya'",     arabic: "الأنبياء",     verses: 112, meaning: "Para Nabi" },
  { number: 22,  latin: "Al-Hajj",        arabic: "الحج",         verses: 78,  meaning: "Haji" },
  { number: 23,  latin: "Al-Mu'minun",    arabic: "المؤمنون",     verses: 118, meaning: "Orang-orang Mukmin" },
  { number: 24,  latin: "An-Nur",         arabic: "النور",        verses: 64,  meaning: "Cahaya" },
  { number: 25,  latin: "Al-Furqan",      arabic: "الفرقان",      verses: 77,  meaning: "Pembeda" },
  { number: 26,  latin: "Asy-Syu'ara'",   arabic: "الشعراء",      verses: 227, meaning: "Para Penyair" },
  { number: 27,  latin: "An-Naml",        arabic: "النمل",        verses: 93,  meaning: "Semut" },
  { number: 28,  latin: "Al-Qasas",       arabic: "القصص",        verses: 88,  meaning: "Kisah" },
  { number: 29,  latin: "Al-'Ankabut",    arabic: "العنكبوت",     verses: 69,  meaning: "Laba-laba" },
  { number: 30,  latin: "Ar-Rum",         arabic: "الروم",        verses: 60,  meaning: "Bangsa Romawi" },
  { number: 31,  latin: "Luqman",         arabic: "لقمان",        verses: 34,  meaning: "Luqman" },
  { number: 32,  latin: "As-Sajdah",      arabic: "السجدة",       verses: 30,  meaning: "Sajdah" },
  { number: 33,  latin: "Al-Ahzab",       arabic: "الأحزاب",      verses: 73,  meaning: "Golongan yang Bersekutu" },
  { number: 34,  latin: "Saba'",          arabic: "سبأ",          verses: 54,  meaning: "Kaum Saba'" },
  { number: 35,  latin: "Fatir",          arabic: "فاطر",         verses: 45,  meaning: "Maha Pencipta" },
  { number: 36,  latin: "Ya Sin",         arabic: "يس",           verses: 83,  meaning: "Ya Sin" },
  { number: 37,  latin: "As-Saffat",      arabic: "الصافات",      verses: 182, meaning: "Yang Berbaris-baris" },
  { number: 38,  latin: "Sad",            arabic: "ص",            verses: 88,  meaning: "Sad" },
  { number: 39,  latin: "Az-Zumar",       arabic: "الزمر",        verses: 75,  meaning: "Rombongan" },
  { number: 40,  latin: "Gafir",          arabic: "غافر",         verses: 85,  meaning: "Yang Mengampuni" },
  { number: 41,  latin: "Fussilat",       arabic: "فصلت",         verses: 54,  meaning: "Yang Dijelaskan" },
  { number: 42,  latin: "Asy-Syura",      arabic: "الشورى",       verses: 53,  meaning: "Musyawarah" },
  { number: 43,  latin: "Az-Zukhruf",     arabic: "الزخرف",       verses: 89,  meaning: "Perhiasan" },
  { number: 44,  latin: "Ad-Dukhan",      arabic: "الدخان",       verses: 59,  meaning: "Kabut" },
  { number: 45,  latin: "Al-Jasiyah",     arabic: "الجاثية",      verses: 37,  meaning: "Berlutut" },
  { number: 46,  latin: "Al-Ahqaf",       arabic: "الأحقاف",      verses: 35,  meaning: "Bukit Pasir" },
  { number: 47,  latin: "Muhammad",       arabic: "محمد",         verses: 38,  meaning: "Nabi Muhammad" },
  { number: 48,  latin: "Al-Fath",        arabic: "الفتح",        verses: 29,  meaning: "Kemenangan" },
  { number: 49,  latin: "Al-Hujurat",     arabic: "الحجرات",      verses: 18,  meaning: "Kamar-kamar" },
  { number: 50,  latin: "Qaf",            arabic: "ق",            verses: 45,  meaning: "Qaf" },
  { number: 51,  latin: "Az-Zariyat",     arabic: "الذاريات",     verses: 60,  meaning: "Angin yang Menerbangkan" },
  { number: 52,  latin: "At-Tur",         arabic: "الطور",        verses: 49,  meaning: "Bukit Tursina" },
  { number: 53,  latin: "An-Najm",        arabic: "النجم",        verses: 62,  meaning: "Bintang" },
  { number: 54,  latin: "Al-Qamar",       arabic: "القمر",        verses: 55,  meaning: "Bulan" },
  { number: 55,  latin: "Ar-Rahman",      arabic: "الرحمن",       verses: 78,  meaning: "Maha Pengasih" },
  { number: 56,  latin: "Al-Waqi'ah",     arabic: "الواقعة",      verses: 96,  meaning: "Hari Kiamat yang Pasti Terjadi" },
  { number: 57,  latin: "Al-Hadid",       arabic: "الحديد",       verses: 29,  meaning: "Besi" },
  { number: 58,  latin: "Al-Mujadilah",   arabic: "المجادلة",     verses: 22,  meaning: "Gugatan" },
  { number: 59,  latin: "Al-Hasyr",       arabic: "الحشر",        verses: 24,  meaning: "Pengusiran" },
  { number: 60,  latin: "Al-Mumtahanah",  arabic: "الممتحنة",     verses: 13,  meaning: "Wanita yang Diuji" },
  { number: 61,  latin: "As-Saf",         arabic: "الصف",         verses: 14,  meaning: "Barisan" },
  { number: 62,  latin: "Al-Jumu'ah",     arabic: "الجمعة",       verses: 11,  meaning: "Hari Jumat" },
  { number: 63,  latin: "Al-Munafiqun",   arabic: "المنافقون",    verses: 11,  meaning: "Orang-orang Munafik" },
  { number: 64,  latin: "At-Tagabun",     arabic: "التغابن",      verses: 18,  meaning: "Pengungkapan Kesalahan" },
  { number: 65,  latin: "At-Talaq",       arabic: "الطلاق",       verses: 12,  meaning: "Talak" },
  { number: 66,  latin: "At-Tahrim",      arabic: "التحريم",      verses: 12,  meaning: "Pengharaman" },
  { number: 67,  latin: "Al-Mulk",        arabic: "الملك",        verses: 30,  meaning: "Kerajaan" },
  { number: 68,  latin: "Al-Qalam",       arabic: "القلم",        verses: 52,  meaning: "Pena" },
  { number: 69,  latin: "Al-Haqqah",      arabic: "الحاقة",       verses: 52,  meaning: "Hari Kiamat" },
  { number: 70,  latin: "Al-Ma'arij",     arabic: "المعارج",      verses: 44,  meaning: "Tempat-tempat Naik" },
  { number: 71,  latin: "Nuh",            arabic: "نوح",          verses: 28,  meaning: "Nabi Nuh" },
  { number: 72,  latin: "Al-Jinn",        arabic: "الجن",         verses: 28,  meaning: "Jin" },
  { number: 73,  latin: "Al-Muzzammil",   arabic: "المزمل",       verses: 20,  meaning: "Orang yang Berselimut" },
  { number: 74,  latin: "Al-Muddassir",   arabic: "المدثر",       verses: 56,  meaning: "Orang yang Berkemul" },
  { number: 75,  latin: "Al-Qiyamah",     arabic: "القيامة",      verses: 40,  meaning: "Hari Kiamat" },
  { number: 76,  latin: "Al-Insan",       arabic: "الإنسان",      verses: 31,  meaning: "Manusia" },
  { number: 77,  latin: "Al-Mursalat",    arabic: "المرسلات",     verses: 50,  meaning: "Malaikat yang Diutus" },
  { number: 78,  latin: "An-Naba'",       arabic: "النبأ",        verses: 40,  meaning: "Berita Besar" },
  { number: 79,  latin: "An-Nazi'at",     arabic: "النازعات",     verses: 46,  meaning: "Yang Mencabut" },
  { number: 80,  latin: "'Abasa",         arabic: "عبس",          verses: 42,  meaning: "Bermuka Masam" },
  { number: 81,  latin: "At-Takwir",      arabic: "التكوير",      verses: 29,  meaning: "Penggulungan" },
  { number: 82,  latin: "Al-Infitar",     arabic: "الانفطار",     verses: 19,  meaning: "Terbelah" },
  { number: 83,  latin: "Al-Mutaffifin",  arabic: "المطففين",     verses: 36,  meaning: "Orang-orang yang Curang" },
  { number: 84,  latin: "Al-Insyiqaq",    arabic: "الانشقاق",     verses: 25,  meaning: "Terbelah" },
  { number: 85,  latin: "Al-Buruj",       arabic: "البروج",       verses: 22,  meaning: "Gugusan Bintang" },
  { number: 86,  latin: "At-Tariq",       arabic: "الطارق",       verses: 17,  meaning: "Yang Datang pada Malam Hari" },
  { number: 87,  latin: "Al-A'la",        arabic: "الأعلى",       verses: 19,  meaning: "Maha Tinggi" },
  { number: 88,  latin: "Al-Gasyiyah",    arabic: "الغاشية",      verses: 26,  meaning: "Hari Kiamat yang Menghilangkan Kesadaran" },
  { number: 89,  latin: "Al-Fajr",        arabic: "الفجر",        verses: 30,  meaning: "Fajar" },
  { number: 90,  latin: "Al-Balad",       arabic: "البلد",        verses: 20,  meaning: "Negeri" },
  { number: 91,  latin: "Asy-Syams",      arabic: "الشمس",        verses: 15,  meaning: "Matahari" },
  { number: 92,  latin: "Al-Lail",        arabic: "الليل",        verses: 21,  meaning: "Malam" },
  { number: 93,  latin: "Ad-Duha",        arabic: "الضحى",        verses: 11,  meaning: "Waktu Duha" },
  { number: 94,  latin: "Asy-Syarh",      arabic: "الشرح",        verses: 8,   meaning: "Pelapangan" },
  { number: 95,  latin: "At-Tin",         arabic: "التين",        verses: 8,   meaning: "Buah Tin" },
  { number: 96,  latin: "Al-'Alaq",       arabic: "العلق",        verses: 19,  meaning: "Segumpal Darah" },
  { number: 97,  latin: "Al-Qadr",        arabic: "القدر",        verses: 5,   meaning: "Kemuliaan" },
  { number: 98,  latin: "Al-Bayyinah",    arabic: "البينة",       verses: 8,   meaning: "Bukti Nyata" },
  { number: 99,  latin: "Az-Zalzalah",    arabic: "الزلزلة",      verses: 8,   meaning: "Guncangan" },
  { number: 100, latin: "Al-'Adiyat",     arabic: "العاديات",     verses: 11,  meaning: "Kuda Perang yang Berlari Kencang" },
  { number: 101, latin: "Al-Qari'ah",     arabic: "القارعة",      verses: 11,  meaning: "Hari Kiamat yang Menggetarkan" },
  { number: 102, latin: "At-Takasur",     arabic: "التكاثر",      verses: 8,   meaning: "Bermegah-megahan" },
  { number: 103, latin: "Al-'Asr",        arabic: "العصر",        verses: 3,   meaning: "Masa" },
  { number: 104, latin: "Al-Humazah",     arabic: "الهمزة",       verses: 9,   meaning: "Pengumpat" },
  { number: 105, latin: "Al-Fil",         arabic: "الفيل",        verses: 5,   meaning: "Gajah" },
  { number: 106, latin: "Quraisy",        arabic: "قريش",         verses: 4,   meaning: "Suku Quraisy" },
  { number: 107, latin: "Al-Ma'un",       arabic: "الماعون",      verses: 7,   meaning: "Bantuan" },
  { number: 108, latin: "Al-Kausar",      arabic: "الكوثر",       verses: 3,   meaning: "Nikmat yang Banyak" },
  { number: 109, latin: "Al-Kafirun",     arabic: "الكافرون",     verses: 6,   meaning: "Orang-orang Kafir" },
  { number: 110, latin: "An-Nasr",        arabic: "النصر",        verses: 3,   meaning: "Pertolongan" },
  { number: 111, latin: "Al-Masad",       arabic: "المسد",        verses: 5,   meaning: "Gejolak Api" },
  { number: 112, latin: "Al-Ikhlas",      arabic: "الإخلاص",      verses: 4,   meaning: "Ikhlas" },
  { number: 113, latin: "Al-Falaq",       arabic: "الفلق",        verses: 5,   meaning: "Waktu Fajar" },
  { number: 114, latin: "An-Nas",         arabic: "الناس",        verses: 6,   meaning: "Manusia" },
];
